### ISSUE TITLE
API connection timeout

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq-markets#1]
@cryptoqween commented on [Mon Jan 08 2018](https://github.com/bisq-network/exchange/issues/1162)

Hi guys, 

we have integrated with you on cryptocompare.com and getting connection timeout from our server, when calling  https://markets.bisq.network/api/trades/?market=btc_eur
Is it possible that our IP is blocked? Can you please let me know who I can contact about this?

Thanks guys
Quynh

---

@ManfredKarrer commented on [Mon Jan 08 2018](https://github.com/bisq-network/exchange/issues/1162#issuecomment-356120311)

@dan-da Could you have a look?

---

@dan-da commented on [Tue Jan 09 2018](https://github.com/bisq-network/exchange/issues/1162#issuecomment-356238795)

hi @cryptoqween.  At present, if your site/bot is issuing more than 180 http requests per minute then the IP will be blocked for 1200 seconds (20 minutes).   If this happens repeatedly, then it will be blocked for longer and longer time periods.   If you would like to send me your IP, I can check if this happened.  Anyway, please try to limit your request frequency as much as possible... eg only a few requests per minute. The server is not so beefy and the API backend is not fully optimized.

Another possibility for timeouts could be that the server is overloaded at certain times by too many requests.  @ManfredKarrer   An improvement we could make is to install cacti or similar load monitoring tool to easily check server load graphs over time.   With increasing API and website load, we are bound to run into hardware limits sooner or later, and best to keep an eye on it.  Other ways to scale include moving api to another domain/server eg api.markets.bisq.network and optimizing software further.  Lowest hanging fruit there should be to re-enable/fix the inter-request caching that for some reason didn't work on that server when deployed.

---

@cryptoqween commented on [Tue Jan 09 2018](https://github.com/bisq-network/exchange/issues/1162#issuecomment-356250736)

Hi @dan-da thanks for the quick response, we'll descrease calls on our side and see what happens

---

@cryptoqween commented on [Tue Jan 09 2018](https://github.com/bisq-network/exchange/issues/1162#issuecomment-356253027)

Is there a way to send you a private message please? @dan-da 
Thanks!

---

@dan-da commented on [Tue Jan 09 2018](https://github.com/bisq-network/exchange/issues/1162#issuecomment-356271014)

@cryptoqween github doesn't seem to support PMs.  If you'd like to post an email addr I will contact you there.

---

@cryptoqween commented on [Tue Jan 09 2018](https://github.com/bisq-network/exchange/issues/1162#issuecomment-356352508)

Can you email me at q at cryptocompare dot come
Thanks @dan-da

**Comment by cbeams** [comment]
@dan-da, could you accept your invitation to join the @bisq-network GitHub organization? I'll assign you to this issue and add you to the @bisq-network/markets-maintainers team.

**Comment by chirhonul** [comment]
Could this issue be closed at this time, or is it still an active problem?

**Comment by ghost** [comment]
(no opinion on closing or not, sorry)
But I profit to say that, from my experience, atm 30 consecutive http requests is enough to have the IP blocked.
If it would be possible to have a bit more, that would be nice.

**Comment by ManfredKarrer** [comment]
@dan-da Could you jump in here?

**Comment by dan-da** [comment]
Present settings are that 30+ requests in 2 minutes will get your IP banned temporarily.

This was put in place to mitigate a ddos attack in early July and it performed well, with website responses going from unusable to quick.

That was before a caching improvement was deployed, so the server should be able to handle more load now.

That said, I don't yet see a compelling reason to raise the limit.   All well-behaving API clients can rate limit to 4 secs between API requests.

An improvement would be to document minimum 4 secs between requests (30 reqs in 2 mins) at https://markets.bisq.network/api/

If the limit is causing any problems for browser sessions, no one has filed an issue for that since the limit was lowered.

**Comment by ghost** [comment]
Thanks for the precisions @dan-da .
I used a timer, but with too small values which seemed to change nothing to the ban.
I'll do it with 4 secs if that makes it.

... I find however that going from 180 req/min to 15 req/min is a bit rude.

**Comment by dan-da** [comment]
>  I find however that going from 180 req/min to 15 req/min is a bit rude.

Agreed it is not ideal.  Again though, it was put in place to mitigate a ddos attack that was killing the site.  Bisq is quite limited on server resources so we have to make do within constraints.

This is the first comments I've seen about it since the limit was lowered.

At this point with the caching in place and current traffic I feel it could safely be raised to 60 reqs in 120 secs ( 2 secs per req ) and still withstand a ddos, if not too huge.

That said, hopefully traffic will continue increasing, so our present server resources will scale approx twice as far if we continue with the 4 secs.  So I'm leaning towards keeping status quo for now.

Either way, I think the most important thing is to document the limit.

anyone want to weigh in on this before I make any change?   any use cases that are seriously adversely impacted by a 4 sec limit?    or has anyone heard complaints of browser sessions being banned?

**Comment by ghost** [comment]
@dan-da , do you have access to the stats for https://markets.bisq.network/api/ frequentation ?
I would be curious to know how much it's used, and if it is growing or not ?

As for the 15 req/min limit, if increasing it puts a risk concerning DDOS, it's ok to let it as it is.
