### ISSUE TITLE
API content type is not json

### ISSUE THREAD

**Issue by fedegrc** [bisq-network/bisq-markets#7]
I'm not sure if this is a real issue or if I'm doing some mistakes.

The verification of the GET response using R console shows that the response content is not json:

> bisq.response   <- GET("https://markets.bisq.network/api/markets")
> http_type(bisq.response)
[1] "**text/html**"
> 

I did the same (basic) test to the github API to check if I'm doing something wrong:

> github.response <- GET("https://api.github.com/repos/bisq-network/bisq-desktop")
> http_type(github.response)
[1] "**application/json**"
> 

The Firefox browser shows the same issue:

![screenshot_20180506_173920](https://user-images.githubusercontent.com/14953828/39677854-705f3882-5158-11e8-9dda-28ae9a20e3d1.png)

![screenshot_20180506_173838](https://user-images.githubusercontent.com/14953828/39677855-7089be04-5158-11e8-9ee6-ce6d58dcad23.png)

**Comment by cbeams** [comment]
The `Content-Type` returned is wrong, but the content itself is valid JSON. Is this something you can work around?

Otherwise, somebody will need to submit a pull request to fix this. @ManfredKarrer is operating the Markets API, but no current @bisq-network contributor is really familiar with the PHP behind it. @dan-da wrote the code, but hasn't been available to maintain it.

I imagine this is an easy fix in the end. Just requires someone familiar with the code, or someone to do the research to figure it out.

**Comment by fedegrc** [comment]
You're right, the content itself is valid JSON and it can processed by R.

**Comment by cbeams** [comment]
Closing as resolved. Thanks for following up @fedegrc.
